---
title: "p8105_hw2_yj2752"
author: Yixuan Jiao
output: github_document
date: "2022-10-03"
---

###Import Library

```{r}
library(tidyverse)
library(readxl)
```


### Problem1

```{r}
nyc_transit = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)) %>%
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

```{r}
select(nyc_transit,station_name,line) %>%
  distinct()
```

```{r}
filter(nyc_transit,ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

```{r}
mean(filter(nyc_transit,vending == 'NO')$entry)
```

```{r}
nyc_transit_tidy <-
  nyc_transit %>%
  pivot_longer(
    route1:route11,
    names_to = 'route_number',
    names_prefix = 'route',
    values_to = 'route_name')
```

```{r}
nyc_transit_tidy %>%
  filter(route_name == 'A') %>%
  select(station_name,line) %>%
  distinct()
```


### Problem2

```{r}
mr_trash_wheel <- 
  read_excel(
    'data/Trash Wheel Collection Data.xlsx',
    range = "A2:N549") %>%
  janitor::clean_names() %>%
  mutate(sports_balls = as.integer(round(sports_balls, digits = 0))) %>%
  add_column(trash_wheel = 'Mr')
```

```{r}
prof_trash_wheel <-
  read_excel(
    'data/Trash Wheel Collection Data.xlsx',
    sheet = 'Professor Trash Wheel',
    range = "A2:M96") %>%
  janitor::clean_names() %>%
  mutate(year = as.character(year)) %>%
  add_column(trash_wheel = 'Professor')
```

```{r}
trash_wheel_tidy <- full_join(mr_trash_wheel,prof_trash_wheel)
```

```{r}
trash_wheel_tidy %>%
  filter(trash_wheel == "Professor") %>%
  pull(weight_tons) %>%
  sum()

trash_wheel_tidy %>%
  filter(year == '2020', trash_wheel == "Mr") %>%
  pull(sports_balls) %>%
  sum()
```

### Problem3

```{r}
pols_month <- 
  read_csv('data/pols-month.csv') %>%
  janitor::clean_names() %>%
  separate(mon, sep = '-', into = c('year','month','day')) %>%
  mutate(month = recode(month, 
  '01' = 'Jan', 
  '02' = 'Feb', 
  '03' = 'Mar', 
  '04' = 'Apr', 
  '05' = 'May',
  '06' = 'Jun',
  '07' = 'Jul',
  '08' = 'Aug',
  '09' = 'Sep',
  '10' = 'Oct',
  '11' = 'Nov',
  '12' = 'Dec')) %>%
  mutate(president = ifelse(prez_dem == 1, 'dem', 'gop')) %>%
  mutate(year = as.numeric(year)) %>%
  select(-prez_dem, -prez_gop, -day)
```

```{r}
snp <- 
  read_csv('data/snp.csv') %>%
  janitor::clean_names() %>%
  separate(date, sep = '/', into = c('month','day','year')) %>%
  mutate(month = recode(month, 
  '1' = 'Jan', 
  '2' = 'Feb', 
  '3' = 'Mar', 
  '4' = 'Apr', 
  '5' = 'May',
  '6' = 'Jun',
  '7' = 'Jul',
  '8' = 'Aug',
  '9' = 'Sep',
  '10' = 'Oct',
  '11' = 'Nov',
  '12' = 'Dec')) %>%
  mutate(year = as.numeric(year)) %>%
  mutate(
    year = case_when(
      year < 40 ~ 2000+year,
      year > 40 ~ 1900+year)) %>%
  relocate(year,month) %>%
  arrange(year) %>%
  select(-day)
```

```{r}
unemployment <- 
  read_csv('data/unemployment.csv') %>%
  rename('year' = 'Year') %>%
  pivot_longer(
    cols = Jan:Dec,
    names_to = 'month',
    values_to = 'unemployment_rate')
```

```{r}
tidy_table_p3 <- 
  pols_month %>%
  left_join(snp) %>%
  left_join(unemployment)
```

